class Post(
    var id: Int,
    var ownerId: Int,
    var fromId: Int,
    val createdBy: Int,
    var date: Int,
    var text: String,
    var replyOwnerId: Int,
    var replyPostId: Int,
    var friendsOnly: Boolean,
    var comments: Comments,
    var copyright: String,
    var likes: Likes,
    var reposts: Reposts,
    var views: Views,
    var postType: PostType,
    var signerId: Int,
    var canPin: Boolean,
    var canDelete: Boolean,
    var canEdit: Boolean,
    var isPinned: Boolean,
    var markedAsAds: Boolean,
    var isFavorite: Boolean,
    var postponedId: Int
) {
}